[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "airflow3-migrator"
version = "1.0.0"
description = "Outil automatisé d'analyse, de rapport et de migration d'Apache Airflow 2 vers Airflow 3."
readme = "README.md"
requires-python = ">=3.9"
authors = [
    { name = "Fabien Chevalier" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Code Generators",
    "Topic :: System :: Systems Administration",
]
dependencies = []

[project.scripts]
airflow3-migrate = "airflow3_migrator.cli:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["airflow3_migrator*"]
